// <auto-generated />
using System;
using ConversionSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConversionSystem.Context.Migrations
{
    [DbContext(typeof(ConversionSystemContext))]
    partial class ConversionSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConversionSystem.Context.Contracts.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Product_Name");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ConversionSystem.Context.Contracts.Models.ProductPresentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PresentationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PresentationType")
                        .HasDatabaseName("IX_ProductPresentation_PresentationType");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPresentations", (string)null);
                });

            modelBuilder.Entity("ConversionSystem.Context.Contracts.Models.ReportResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductPresentationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ViewToPaymentRatio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_ReportResult_Id");

                    b.HasIndex("ProductPresentationId");

                    b.ToTable("ReportResults", (string)null);
                });

            modelBuilder.Entity("ConversionSystem.Context.Contracts.Models.ProductPresentation", b =>
                {
                    b.HasOne("ConversionSystem.Context.Contracts.Models.Product", "Product")
                        .WithMany("ProductPresentation")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ConversionSystem.Context.Contracts.Models.ReportResult", b =>
                {
                    b.HasOne("ConversionSystem.Context.Contracts.Models.ProductPresentation", "ProductPresentation")
                        .WithMany("ReportResult")
                        .HasForeignKey("ProductPresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductPresentation");
                });

            modelBuilder.Entity("ConversionSystem.Context.Contracts.Models.Product", b =>
                {
                    b.Navigation("ProductPresentation");
                });

            modelBuilder.Entity("ConversionSystem.Context.Contracts.Models.ProductPresentation", b =>
                {
                    b.Navigation("ReportResult");
                });
#pragma warning restore 612, 618
        }
    }
}
